### PR TITLE
small tweaks for lizard spock functionality

### PR DESCRIPTION
**Pull request by p1cxi**
Hey dude, was bored tonight so I though i'd help out with the project I just saw you create lol hope you don't mind.

image

I noticed in your readme you wanted to add extendibility for more weapons, so I have given you a way to do that it uses arrays and object to dictate what weapons are "weak"/"strong" as compared to another one.

image

Along with this I made the logic for comparing each weapon more seamless too, the pattern of looking for something in an array when validating text is quite nice to do stuff definitely start using it c:

image

### CODE REVIEW

**Comment by Electrolytful** [comment]
Wow this looks really good, I would like to talk about it more with you tomorrow at some point if possible.

**Comment by p1cxi** [comment]
for sure dude i'm down to talk about it, anything in particular that's confusing or?

i forked your repo to add the changes so if you wanted you could go to the other url and clone to see how the tweaks would effect the app before committing them, I made sure everything works before hand tho ofc ^^

https://github.com/sord-dev/rock-paper-scissors-terminal

**Comment by Electrolytful** [comment]
Nothing too confusing I saw your code for your own game before hand so I understand the way you implemented your weapons and stuff. I would just like to see it through with you in person before merging lol.

**Comment by p1cxi** [comment]
Gotchu gotchu, I'll see you tomorrow my bro 😄

**Pull request merged**
